# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Static Analysis

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/common.txt
        python setup.py develop
        pip install mypy pylint bandit
    - name: Lint with pylint
      run: |
        pylint purpleair
    - name: Static Analysis with mypy
      run: |
        mypy . --ignore-missing-imports
    - name: Security Analysis with Bandit
      run: |
        bandit -rll purpleair
    - name: Test run
      run: |
